name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: |
          mkdir -p build
          cmake -S . -B build
      - name: Build
        run: |
          cmake --build build --config Release
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build

  Test_Add:
    name: Test_Add
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build
      - name: Run Test_Add
        run: |
          cd build
          ctest -R t1 -V

  Test_Sub:
    name: Test_Sub
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build
      - name: Run Test_Sub
        run: |
          cd build
          ctest -R t2 -V

  Test_Mul:
    name: Test_Mul
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build
      - name: Run Test_Mul
        run: |
          cd build
          ctest -R t3 -V

  Test_Div:
    name: Test_Div
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build
      - name: Run Test_Div
        run: |
          cd build
          ctest -R t4 -V

  Test_Car:
    name: Test_Car
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build
      - name: Run Test_Car
        run: |
          cd build
          ctest -R t5 -V

  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_Sub, Test_Mul, Test_Div, Test_Car]
    steps:
      - name: Deploy message
        run: echo "DÃ©ploiement de la solution"
